apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace:  nginx-deployment
  labels:
    env:  demo
    type: frontend
spec:
  containers:
  - name: nginx-container
    image:  nginx
    ports:
      - containerPort:  80
        
