apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace:  nginx-deployment
spec:
  type: NodePort
  selector: 
    env:  demo
    type: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
